- hosts: devlaptops
  tasks:

  - name: remove conflicting packages
    sudo: yes
    apt:
      name: "{{item}}"
      state: absent
    with_items:
      - account-plugin-google
      - unity-scope-gdriv


- hosts: devlaptops
  tasks:

  - name: Add Canonical partner repo (for skype etc.)
    sudo: yes
    apt_repository:
      repo: deb http://archive.canonical.com/ubuntu xenial partner
      state: present

  - name: Add apt-fast repository
    sudo: yes
    apt_repository:
      repo: 'ppa:saiarcot895/myppa'
      state: present

  - name: install packages
    sudo: yes
    apt:
      name: "{{item}}"
      update_cache: yes
      state: present
    with_items:
      - tree
      - htop
      - ack-grep
      - python-dev
      - python3-dev
      - vim
      - git
      - gcalcli
      - virtualbox
      - lynx
      - vagrant
      - valgrind
      - powertop
      - iotop
      - mesa-utils
      - tmux
      - rdiff-backup
      - rsync
      - anki
      - docker.io
      - docker-compose
      - vim-syntax-docker
      - cmake
      - clang
      - xmonad
      - trayer
      - suckless-tools
      - xmobar
      - xournal
      - evince
      - virtualenvwrapper
      - rhythmbox
      - dia
      - prey
      - youtube-dl
      - thunar-dropbox-plugin
      - evince
      - vlc
      - arandr
      - sc
      - sshfs
      - simple-scan
      - swig
      - mc
      - exuberant-ctags
      - ccache
      - preload
      - bmon
      - vnstat
      - nethogs
      - ecryptfs-utils
      # for prey
      - scrot
      - mpg123
      - giblib1
      - libimlib2
      - libid3tag0
      - libgif7
      - tig
      - gt5
      - baobab
      - checkinstall
      - psensor
      - pavucontrol
      - wicd-curses
      - kubuntu-desktop
      - kde-config-telepathy-accounts
      - thunderbird
      - nexuiz
      - playonlinux
      - ipython  
      - volti
      - feh
      - lm-sensors
      - skype
      - apt-fast
      - i3status
      # YouCompleteMe vim plugin
      - ycmd
      - build-essential
      - xbacklight
      - traceroute

      # VPN (20160301 - VPN crashes with double free error if .ike/sites/xxx not found)
      - ike
      # - ike-qtgui

      # ike build dependencies
      # - libssl-dev
      # - libedit-dev
      # - flex
      # - bison


      # packages not available
      # apt-fast
      # skype
      # firebird

# #         #  - user
        # name: bb
        #      groups: docker
        # append: yes

  - name: Plasma conf dir  | ensure dir exists
    file: path=~/.config/plasma-workspace/ state=directory

  - name: Kde & xmonad | Make xmonad window manager for KDE
    template: src=templates/xmonad/set_window_manager.sh.j2 dest=~/.config/plasma-workspace/set_window_manager.sh

  - name: Fix touch pad palm detection (might not work correctly
    # http://seb.mamessier.com/dell-xps-15-9550-ubuntu-16-04/
    sudo: yes
    lineinfile: 
        destfile: /etc/modprobe.d/blacklist.conf 
        regexp: "^blacklist i2c_designware-platform"
        line: blacklist i2c_designware-platform

  - name: Add Samsung Universal printer driver repo
    sudo: yes
    apt_repository:
        repo: deb http://www.bchemnet.com/suldr/ debian extra

  - name: Fetch and install keyring for Samsung Universal Printer repo
    sudo: yes
    shell: |
        wget http://www.bchemnet.com/suldr/pool/debian/extra/su/suldr-keyring_2_all.deb
        dpkg -i suldr-keyring_2_all.deb
        rm suldr-keyring_2_all.deb

  - name: Install Samsung Universal printer driver
    sudo: yes
    apt:
      name: "{{item}}"
      state: present
      update_cache: yes
    with_items:
        - suld-driver-4.00.39
        - suld-configurator-2-qt4


  - name: Add nvidia repo
    sudo: yes
    apt_repository:
        repo: 'ppa:graphics-drivers/ppa'

#   - name: Install nvidia drivers
#     # requires switching off UEFI
#     # causing ansible playbook to hang
#     apt:
#         name: "{{item}}"
#         state: present
#         update_cache: yes
#     with_items:
#         - nvidia-375
#         - nvidia-prime
# 
#   - name: Add repo for nvidia prime indicator
#     apt_repository:
#         repo: 'ppa:nilarimogard/webupd8'

    #   - name: Install nvidia prime indicator 
    #     apt:
    #    name: "{{item}}"
    #    state: present
    #    update_cache: yes
    #     with_items:
    #   - prime-indicator
    #

  - name: Install .vimrc file
    template:
        src: templates/vimrc.j2
        dest: ~/.vimrc

  - name: vim bundle dir  | ensure dir exists
    file: path=~/.vim/bundle state=directory

  - name: Install vundle (vim plugin manager)
    git:
        repo: https://github.com/VundleVim/Vundle.vim.git
        dest: ~/.vim/bundle/Vundle.vim 

  - name: Install vim plugins with vundle
    shell: vim +PluginInstall +qall 2&>/dev/null

  - name: Install vim plugin YouCompleteMe
    shell: ./install.py --clang-completer
    args:
        chdir: '~/.vim/bundle/YouCompleteMe'

