- hosts: devlaptops
  tasks:
  - name: remove conflicting packages
    sudo: yes
    apt:
      name: "{{item}}"
      state: absent
    with_items:
      - account-plugin-google
      - unity-scope-gdriv

- hosts: devlaptops
  tasks:
  - name: install packages
    sudo: yes
    apt:
      name: "{{item}}"
      state: present
    with_items:
      - htop
      - vim
      - git
      - gcalcli
      - virtualbox
      - lynx
      - vagrant
      - valgrind
      - powertop
      - iotop
      - mesa-utils
      - tmux
      - rdiff-backup
      - rsync
      - anki
      - docker.io
      - docker-compose
      - vim-syntax-docker
      - clang
      - xmonad
      - trayer
      - suckless-tools
      - xmobar
      - xournal
      - evince
      - virtualenvwrapper
      - rhythmbox
      - dia
      - prey
      - youtube-dl
      - thunar-dropbox-plugin
      - evince
      - vlc
      - arandr
      - sc
      - sshfs
      - simple-scan
      - swig
      - mc
      - exuberant-ctags
      - ccache
      - preload
      - bmon
      - vnstat
      - nethogs
      - ecryptfs-utils
      # for prey
      - scrot
      - mpg123
      - giblib1
      - libimlib2
      - libid3tag0
      - libgif7
      - tig
      - gt5
      - baobab
      - checkinstall
      - psensor
      - pavucontrol
      - wicd-curses
      - kubuntu-desktop
      - kde-config-telepathy-accounts
      - thunderbird
      

      # packages not available
      # apt-fast
      # skype
      # firebird

        #  - user
        # name: bb
        #      groups: docker
        # append: yes
  - name: Plasma conf dir  | ensure dir exists
    file: path=/home/bb/.config/plasma-workspace/ state=directory
  - name: Kde & xmonad | Make xmonad window manager for KDE
    template: src=templates/xmonad/set_window_manager.sh.j2 dest=/home/bb/.config/plasma-workspace/set_window_manager.sh

  - name: Fix touch pad palm detection (might not work correctly
    # http://seb.mamessier.com/dell-xps-15-9550-ubuntu-16-04/
    sudo: yes
    lineinfile: 
        destfile: /etc/modprobe.d/blacklist.conf 
        regexp: "^blacklist i2c_designware-platform"
        line: blacklist i2c_designware-platform

  - name: Add nvidia repo
    apt_repository:
        repo: 'ppa:graphics-drivers/ppa'

  - name: Install nvidia drivers
    # requires switching off UEFI
    # causing ansible playbook to hang
    apt:
        name: "{{item}}"
        state: present
        update_cache: yes
    with_items:
        - nvidia-375
        - nvidia-prime

  - name: Add repo for nvidia prime indicator
    apt_repository:
        repo: 'ppa:nilarimogard/webupd8'

  - name: Install nvidia prime indicator 
    apt:
        name: "{{item}}"
        state: present
        update_cache: yes
    with_items:
        - prime-indicator
