---
- name: Create PyCharm installation directory
  become: yes
  become_user: root
  file: name={{pycharm_install_dir}} state=directory

- name: Fetch PyCharm
  become: yes
  become_user: root
  get_url:
    url: "{{pycharm_url}}"
    dest: /tmp/{{pycharm_archive}}
  notify:
      - install pycharm

- name: create PyCharm link
  become: yes
  become_user: root
  file: src={{pycharm_install_dir}}/{{pycharm_dir}}/bin/pycharm.sh dest=/usr/local/bin/pycharm   state=link force=yes


- name: Install IdeaVim plugin config
  template: 
    src: templates/idearc.j2
    dest: ~/.idearc
