---

- name: install packages for vim
  sudo: yes
  apt:
    name: "{{item}}"
    state: present
  with_items:
    - silversearcher-ag
    - ack-grep
    - vim
    - vim-syntax-docker
    - exuberant-ctags
    # YouCompleteMe vim plugin
    - ycmd
