---
- name: Install Samsung Universal printer driver
  sudo: yes
  apt:
    name: "{{item}}"
    state: present
    update_cache: yes
  with_items:
      - suld-driver-4.00.39
      - suld-configurator-2-qt4

- name: Install vundle
  git:
    repo: https://github.com/VundleVim/Vundle.vim.git
    dest: ~/.vim/bundle/Vundle.vim 

- name: Install vim plugins with vundle
  shell: vim +PluginInstall +qall 2&>/dev/null

- name: Install vim plugin YouCompleteMe
  shell: ./install.py --clang-completer
  args:
    chdir: '~/.vim/bundle/YouCompleteMe'
