---

- name: install packages
  sudo: yes
  apt:
    name: "{{item}}"
    state: present
  with_items:
    - tree
    - silversearcher-ag
    - resolvconf
    - rdiff-backup
    - htop
    - ack-grep
    - python-dev
    - python-pip
    - python3-dev
    - vim
    - git
    - gcalcli
    - virtualbox
    - lynx
    - vagrant
    - valgrind
    - powertop
    - iotop
    - mesa-utils
    - tmux
    - rdiff-backup
    - rsync
    - anki
    - docker.io
    # TOO OLD: 1.5.2
    # - docker-compose
    - vim-syntax-docker
    - cmake
    - clang
    - xmonad
    - trayer
    - suckless-tools
    - xmobar
    - xournal
    - evince
    - virtualenvwrapper
    - rhythmbox
    - dia
    - prey
    - youtube-dl
    - thunar-dropbox-plugin
    - evince
    - vlc
    - arandr
    - sc
    - sshfs
    - simple-scan
    - swig
    - mc
    - exuberant-ctags
    - ccache
    - preload
    - bmon
    - vnstat
    - nethogs
    - ecryptfs-utils
    # for prey
    - scrot
    - mpg123
    - giblib1
    - libimlib2
    - libid3tag0
    - libgif7
    - tig
    - gt5
    - baobab
    - checkinstall
    - psensor
    - pavucontrol
    - wicd-curses
      # - kubuntu-desktop
    # - kde-config-telepathy-accounts
    - thunderbird
    - nexuiz
    - playonlinux
    - ipython  
    - volti
    - feh
    - lm-sensors
    - skype
    - apt-fast
    - i3status
    - i3lock
    - xautolock
    # YouCompleteMe vim plugin
    - ycmd
    - build-essential
    - xbacklight
    - traceroute

    # Frac build
    - libbz2-dev
    - gperf
    - re2c
    - libsqlite3-dev
    ## for building Python 2.7
    - gcc-multilib
    - g++-multilib
    - libffi-dev
    - libffi6
    - libffi6-dbg
    - python-crypto
    - python-mox3
    - python-pil
    - python-ply
    - libssl-dev
    - zlib1g-dev
    - libbz2-dev
    - libexpat1-dev
    - libbluetooth-dev
    - libgdbm-dev
    - dpkg-dev
    - quilt
    - autotools-dev
    - libreadline-dev
    - libtinfo-dev
    - libncursesw5-dev
    - tk-dev
    - blt-dev
    - libssl-dev
    - zlib1g-dev
    - libbz2-dev
    - libexpat1-dev
    - libbluetooth-dev
    - libsqlite3-dev
    - libgpm2
    - mime-support
    - netbase
    - net-tools
    - bzip2
    - mercurial

    ## for swig
    - libpcre3-dev

    
    ######## actually, should use fractal/scripts/setup_ubuntu_16.sh
    ## For building fractal repo
    - libgoogle-perftools-dev
    - texlive-latex-base
    - texlive-fonts-recommended

    # VPN (20160301 - VPN crashes with double free error if .ike/sites/xxx not found)
    - ike
    # - ike-qtgui

    # ike build dependencies
    # - libssl-dev
    # - libedit-dev
    # - flex
    # - bison


    # packages not available
    # apt-fast
    # skype
    # firebird

# #         #  - user
      # name: bb
      #      groups: docker
      # append: yes



- name: Plasma conf dir  | ensure dir exists
  file: path=~/.config/plasma-workspace/ state=directory

- name: Kde & xmonad | Make xmonad window manager for KDE
  template: src=templates/xmonad/set_window_manager.sh.j2 dest=~/.config/plasma-workspace/set_window_manager.sh

- name: Fix touch pad palm detection (might not work correctly
  # http://seb.mamessier.com/dell-xps-15-9550-ubuntu-16-04/
  sudo: yes
  lineinfile: 
      destfile: /etc/modprobe.d/blacklist.conf 
      regexp: "^blacklist i2c_designware-platform"
      line: blacklist i2c_designware-platform

- name: Fetch and install keyring for Samsung Universal Printer repo
  get_url:
    url: http://www.bchemnet.com/suldr/pool/debian/extra/su/suldr-keyring_2_all.deb
    dest: /tmp/suldr-keyring_2_all.deb
  notify:
    - Install Samsung Universal printer driver

- name: Add Samsung Universal printer driver repo
  sudo: yes
  apt_repository:
      repo: deb http://www.bchemnet.com/suldr/ debian extra
  notify:
    -  Update APT cache
    - Install Samsung Universal printer driver 


# - name: Add nvidia repo
#  sudo: yes
#  apt_repository:
#      repo: 'ppa:graphics-drivers/ppa'

#   - name: Install nvidia drivers
#     # requires switching off UEFI
#     # causing ansible playbook to hang
#     apt:
#         name: "{{item}}"
#         state: present
#         update_cache: yes
#     with_items:
#         - nvidia-375
#         - nvidia-prime
# 
#   - name: Add repo for nvidia prime indicator
#     apt_repository:
#         repo: 'ppa:nilarimogard/webupd8'

  #   - name: Install nvidia prime indicator 
  #     apt:
  #    name: "{{item}}"
  #    state: present
  #    update_cache: yes
  #     with_items:
  #   - prime-indicator
  #

- name: Install .vimrc file
  template:
      src: templates/vimrc.j2
      dest: ~/.vimrc

- name: vim bundle dir  | ensure dir exists
  file: path=~/.vim/bundle state=directory
  notify:
  - Install vundle
  - Install vim plugins with vundle
  - Install vim plugin YouCompleteMe




###### misc stuff to add to Ansible scripts:
# ~/.gitconfig
#
