---
- name: remove conflicting packages
  sudo: yes
  apt:
    name: "{{item}}"
    state: absent
  with_items:
    - account-plugin-google
    - unity-scope-gdriv


- name: Add Canonical partner repo (for skype etc.)
  sudo: yes
  apt_repository:
    repo: deb http://archive.canonical.com/ubuntu xenial partner
    state: present
  notify:
    -  Update APT cache

- name: Add apt-fast repository
  sudo: yes
  apt_repository:
    repo: 'ppa:saiarcot895/myppa'
    state: present
  notify:
    -  Update APT cache


- name: install common packages
  sudo: yes
  apt:
    name: "{{item}}"
    state: present
  with_items:
    - geeqie
    - speedtest-cli
    - smartmontools
    - gsmartcontrol
    - gparted
    - moreutils
    - valgrind
    - kcachegrind
    - autoconf
    - automake
    - m4
    - libtool
###     - cups
###     - libcups2
###     - libcupscgi1
###     - libcupsmime1
###     - cups-core-drivers
###     - cups-daemon
    - openssh-server
    - apt-file
    - mmv
    - tree
    - silversearcher-ag
    - dos2unix
    - rdiff-backup
    - htop
    - nmap
    - ack-grep
    - sloccount
    - nginx
    - kdiff3-qt
    - shutter
    - python-gtk2-dev  # unlisted dependency of diffuse
    - diffuse
    - python-dev
    - python-pip
    - cython
    - pylint
    - flake8
    - prospector
    - pymetrics
    - python-mccabe
    - python-coverage
    - python3-dev
    - vim
    - git
    - git-annex
    - bup
    - git-gui
    - gcalcli
    - gimp
    - virtualbox
    - lynx
    - vagrant
    - valgrind
    - ddd
    - nemiver
    - cgdb
    - powertop
    - iotop
    - mesa-utils
    - tmux
    - tmuxinator
    - xclip
    - rdiff-backup
    - duply
    - sendmail
    - rsync
    - anki
    - vim-syntax-docker
    - cmake
    - clang
    - clang-format-4.0
    - clang-tidy
    - cccc
    - pmccabe
    - xournal
    - evince
    - virtualenvwrapper
    - rhythmbox
    - dia
    - prey
    - youtube-dl
    - thunar-dropbox-plugin
    - evince
    - vlc
    - arandr
    - sc
    - sshfs
    - simple-scan
    - swig
    - mc
    - exuberant-ctags
    - ccache
    - preload
    - bmon
    - vnstat
    - nethogs
    - ecryptfs-utils
    # for prey
    - scrot
    - mpg123
    - giblib1
    - libimlib2
    - libid3tag0
    - libgif7
    - tig
    - gt5
    - baobab
    - checkinstall
    - psensor
    - pavucontrol
      # - wicd-curses
      # - kubuntu-desktop
    # - kde-config-telepathy-accounts
    - thunderbird
    - playonlinux
    - ipython  
    - volti
    - feh
    - lm-sensors
    - skypeforlinux
    - apt-fast
    - i3status
    - i3lock
    - xautolock
    # YouCompleteMe vim plugin
    - ycmd
    - build-essential
    - xbacklight
    - traceroute
    - cabal-install
    - libsdl2-dev
    - libsdl2-image-dev
    - golang-go
    - nagios3
    - reiser4progs
    - reiserfsprogs
    - fstransform

    # packages not available
    # apt-fast
    # skype
    # firebird

# We only want nginx to be available, not serving anything
- name: disable nginx
  sudo: yes
  systemd:
    name: nginx
    state: stopped
    enabled: false

- name: Fetch keyring for Samsung Universal Printer repo
  get_url:
    url: http://www.bchemnet.com/suldr/pool/debian/extra/su/suldr-keyring_2_all.deb
    dest: /tmp/suldr-keyring_2_all.deb

- name: Install keyring for Samsung Universal Printer repo
  sudo: yes
  shell: dpkg -i /tmp/suldr-keyring_2_all.deb


- name: Add Samsung Universal printer driver repo
  sudo: yes
  apt_repository:
      repo: deb http://www.bchemnet.com/suldr/ debian extra
  notify:
    -  Update APT cache
    - Install Samsung Universal printer driver 

- name: .pep8 configuration
  template: src=templates/pep8.j2 dest=~/.pep8

- name: Download nodejs
  shell: curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
      
- name: Install nodejs
  sudo: yes
  shell: apt-get install -y nodejs

