---


- name: Install Docker repository key
  sudo: yes
  apt_key:
    id: 58118E89F3A912897C070ADBF76221572C52609D
    keyserver: hkp://p80.pool.sks-keyservers.net:80
    state: present

- name: Add Docker repository
  sudo: yes
  apt_repository:
    repo: deb https://apt.dockerproject.org/repo {{ ansible_lsb.id|lower }}-{{ ansible_lsb.codename|lower }} main
    state: present
  notify:
    - Update APT cache
    - Install packages for docker



# We need support for syntax >= 2 
- name: Install docker-compose
  sudo: yes
  get_url: 
      url: https://github.com/docker/compose/releases/download/1.11.1/run.sh
      dest: /usr/local/bin/docker-compose
      mode: ugo+x
