---

- name: Install vundle
  git:
    repo: https://github.com/VundleVim/Vundle.vim.git
    dest: ~/.vim/bundle/Vundle.vim 

- name: Install vim plugins with vundle
  shell: vim +PluginInstall +qall 2&>/dev/null

- name: Install vim plugin YouCompleteMe
  shell: ./install.py --clang-completer
  args:
    chdir: '~/.vim/bundle/YouCompleteMe'

- name: Update APT cache
  shell: apt-get update
