---
- name: install packages for vim
  become: yes
  become_user: root
  apt:
    name: "{{item}}"
    state: present
  with_items:
    - python-pep8
    - python-autopep8
    - silversearcher-ag
    - ack-grep
    - exuberant-ctags
    - cscope
    - vim
    - vim-syntax-docker
    - exuberant-ctags
    # YouCompleteMe vim plugin
    - ycmd

- name: Install .vimrc file
  template:
      src: templates/vimrc.j2
      dest: ~/.vimrc
  notify:
  - Install vim plugins with vundle

- name: vim bundle dir  | ensure dir exists
  file: path=~/.vim/bundle state=directory
  notify:
  - Install vundle
  - Install vim plugins with vundle
  - Install vim plugin YouCompleteMe
