---

- name: Add TouchPad indicator repo
  become: yes
  become_user: root
  apt_repository:
    repo: 'ppa:atareao/atareao'
    state: present
  notify:
    -  Update APT cache

- name: install packages for xmonad
  become: yes
  become_user: root
  apt:
    name: "{{item}}"
    state: present
  with_items:
    - xmonad
    - trayer
    - suckless-tools
    - xmobar
    - xournal
    - vlc
    - volti
    - feh
    - i3status
    - i3lock
    - xautolock
    - xbacklight
    - touchpad-indicator


- name: .xmonad dir
  file: path=~/.xmonad/scripts state=directory

- name: xmonad.hs (xmonad config file)
  template: src=templates/xmonad.hs.j2 dest=~/.xmonad/xmonad.hs
  notify:
    - recompile xmonad

  #- name: Install TouchPad toggle script
  #template: src=templates/scripts/touchpad-toggle.sh.j2 dest=~/.xmonad/scripts/touchpad-toggle.sh
  #args: 
  #    mode: u+x
 
- name: Create touchpad-indicator config dir
  file: path=~/.config/touchpad-indicator state=directory

- name: Install touchpad-indicator config
  template: src=templates/touchpad-indicator.conf.j2 dest=~/.config/touchpad-indicator/touchpad-indicator.conf

- name: .xsession file
  template: src=templates/xsession.j2 dest=~/.xsession
