---

- name: install packages for xmonad
  sudo: yes
  apt:
    name: "{{item}}"
    state: present
  with_items:
    - xmonad
    - trayer
    - suckless-tools
    - xmobar
    - xournal
    - vlc
    - volti
    - feh
    - i3status
    - i3lock
    - xautolock
    - xbacklight


- name: .xmonad dir
  file: path=~/.xmonad/scripts state=directory

- name: xmonad.hs (xmonad config file)
  template: src=templates/xmonad.hs.j2 dest=~/.xmonad/xmonad.hs
  notify:
    - recompile xmonad

- name: Install TouchPad toggle script
  template: src=templates/scripts/touchpad-toggle.sh.j2 dest=~/.xmonad/scripts/touchpad-toggle.sh

- name: .xsesion file
  template: src=templates/xsession.j2 dest=~/.xsession
